export const ACTIONS = {
    ADD_PENSION: 'ADD_PENSION',
    EDIT_PENSION: 'EDIT_PENSION',
    REMOVE_PENSION: 'REMOVE_PENSION',
    TRANSFER_INTO: 'TRANSFER_INTO',
    RESET_CONTEXT: 'RESET_CONTEXT',
    RESET_ADD_PENSION: 'RESET_ADD_PENSION',
    ADD_ANOTHER_PENSION: 'ADD_ANOTHER_PENSION',
    START_JOURNEY: 'START_JOURNEY',
    SET_IS_REVIEW: 'SET_IS_REVIEW',
    SET_IS_EDIT: 'SET_IS_EDIT',
    SET_ACTIVE_PENSION_INDEX: 'SET_ACTIVE_PENSION_INDEX',
    SET_IS_TEIR_TWO_ACTION: 'SET_IS_TEIR_TWO_ACTION',
    SET_CANCEL_ACTION: 'SET_CANCEL_ACTION'
  };
  